version: '3.8'
services:

  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: seQWERiTY
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
