spring:
  application:
    name: seQWERiTY
  devtools:
    livereload:
      enabled: false

logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO}
    by.pochitately.seqwerity: ${LOG_LEVEL:INFO}