server:
  servlet:
    context-path: /api
  port: 9090

spring:
  application:
    name: seQWERiTY
  devtools:
    livereload:
      enabled: false
  data:
    mongodb:
      uri: mongodb://seQWERiTY:paSSw0rd@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/seQWERiTY
  jackson:
    default-property-inclusion: non_empty

logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO}
    by.pochitately.seqwerity: ${LOG_LEVEL:INFO}
